kind: Service
apiVersion: v1
metadata:
  name: druid-coordinator
  labels:
    app: druid
    component: coordinator
    release: druid
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http
  selector:
    app: druid
    component: coordinator
    release: druid
  type: ClusterIP
  sessionAffinity: None
