kind: ConfigMap
apiVersion: v1
metadata:
  name: druid
  labels:
    app: druid
    release: druid
data:
  druid_zk_service_host: 'druid-zookeeper-headless:2181'
  druid_metadata_storage_connector_password: druid
  druid_metadata_storage_connector_connectURI: 'jdbc:postgresql://druid-postgresql:5432/druid'
  druid_indexer_logs_type: file
  druid_emitter_logging_logLevel: debug
  druid_emitter_http_recipientBaseUrl: 'http://druid_exporter_url:druid_exporter_port/druid'
  druid_emitter: noop
  druid_metadata_storage_type: postgresql
  druid_extensions_loadList: >-
    ["druid-histogram", "druid-datasketches", "druid-lookups-cached-global",
    "postgresql-metadata-storage", "druid-s3-extensions"]
  druid_metadata_storage_connector_user: druid
  druid_indexer_logs_directory: /opt/data/indexing-logs
  DRUID_USE_CONTAINER_IP: 'true'
  druid_storage_type: local
