kind: Deployment
apiVersion: apps/v1
metadata:
  name: druid-broker
  labels:
    app: druid
    component: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid
      component: broker
      release: druid
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: druid
        component: broker
        release: druid
    spec:
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /status/health
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: druid
          livenessProbe:
            httpGet:
              path: /status/health
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DRUID_MAXDIRECTMEMORYSIZE
              value: 400m
            - name: DRUID_XMS
              value: 512m
            - name: DRUID_XMX
              value: 512m
            - name: druid_processing_buffer_sizeBytes
              value: '50000000'
            - name: druid_processing_numMergeBuffers
              value: '2'
            - name: druid_processing_numThreads
              value: '1'
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: druid
          image: 'apache/druid:0.18.1'
          args:
            - broker
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
