kind: Service
apiVersion: v1
metadata:
  name: druid-postgresql
  labels:
    app: postgresql
    release: druid
spec:
  ports:
    - name: tcp-postgresql
      protocol: TCP
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app: postgresql
    release: druid
    role: master
  type: ClusterIP
  sessionAffinity: None
